# Generated by Django 4.2.11 on 2026-08-13 21:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("cadferramentas", "0002_ferramenta_responsavel"),
    ]

    operations = [
        migrations.CreateModel(
            name="HistoricoAlteracaoFerramenta",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("campo", models.CharField(max_length=100)),
                ("valor_anterior", models.TextField(blank=True, null=True)),
                ("valor_novo", models.TextField(blank=True, null=True)),
                ("data_hora", models.DateTimeField(auto_now_add=True)),
                (
                    "ferramenta",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="historicos",
                        to="cadferramentas.ferramenta",
                    ),
                ),
                (
                    "usuario",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="historicos_ferramentas",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-data_hora"],
            },
        ),
    ]
