# Generated by Django 4.2.30 on 2026-08-14 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadferramentas', '0003_historicoalteracaoferramenta'),
    ]

    operations = [
        migrations.AddField(
            model_name='ferramenta',
            name='possui_patrimonio',
            field=models.CharField(blank=True, default='sim', max_length=10),
        ),
        migrations.AlterField(
            model_name='ferramenta',
            name='patrimonio',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
