# Generated by Django 6.0.6 on 2026-06-21 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadptm', '0002_item_alter_patrimonio_tipo'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Item',
        ),
        migrations.AlterField(
            model_name='patrimonio',
            name='tipo',
            field=models.CharField(choices=[('proprio', 'Proprio'), ('terceiro', 'Terceiro')], max_length=100),
        ),
    ]
