# Generated by Django 6.0.6 on 2026-07-15 18:15

from django.db import migrations, models
from django.utils import timezone


class Migration(migrations.Migration):

    dependencies = [
        ("pontoele", "0002_remove_servidor_foto_referencia_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="servidor",
            name="data_cadastro",
            field=models.DateTimeField(auto_now_add=True, default=timezone.now),
            preserve_default=False,
        ),
    ]
