# Generated by Django 6.0.6 on 2026-07-17 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pontoele", "0003_servidor_data_cadastro"),
    ]

    operations = [
        migrations.AddField(
            model_name="servidor",
            name="bairro",
            field=models.CharField(default="", max_length=100),
        ),
        migrations.AddField(
            model_name="servidor",
            name="cep",
            field=models.CharField(default="", max_length=9),
        ),
        migrations.AddField(
            model_name="servidor",
            name="cidade",
            field=models.CharField(default="", max_length=100),
        ),
        migrations.AddField(
            model_name="servidor",
            name="cpf",
            field=models.CharField(default="", max_length=14, unique=True),
        ),
        migrations.AddField(
            model_name="servidor",
            name="data_nascimento",
            field=models.DateField(default="2000-01-01"),
        ),
        migrations.AddField(
            model_name="servidor",
            name="email",
            field=models.EmailField(default="naoinformado@example.com", max_length=254),
        ),
        migrations.AddField(
            model_name="servidor",
            name="endereco",
            field=models.CharField(default="", max_length=300),
        ),
        migrations.AddField(
            model_name="servidor",
            name="rg",
            field=models.CharField(default="", max_length=20),
        ),
        migrations.AddField(
            model_name="servidor",
            name="telefone",
            field=models.CharField(default="", max_length=20),
        ),
        migrations.AddField(
            model_name="servidor",
            name="uf",
            field=models.CharField(default="", max_length=2),
        ),
    ]
