# Generated by Django 5.1.2 on 2026-08-20 12:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("pontoele", "0006_alter_servidor_face_encoding"),
    ]

    operations = [
        migrations.AlterModelTable(
            name="servidor",
            table="pontoele_servidor",
        ),
    ]
